### ISSUE TITLE
Upload new or updated variables (e.g. emission factors or activity data or other variables including source references and other documentation) in bulk to the database.

### ISSUE THREAD

**Issue by nickwxo** [slashroots/undp-ghg#19] opened 2017-07-03 16:10 UTC
As an Inventory Manager or Sector Export I want to be able to upload new or updated variables (e.g. emission factors or activity data or other variables including source references and other documentation) in bulk to the database so that the system will update the new inventory with the new variables.

Acceptance Criteria : 

- Defined inventory data is successfully uploaded when it is submitted in the defined format and file type (preferrably .xls)
- System warns uploader if data points are going to be overwritten for variables for years already present in the database.  Uploader can abort if needed or roll back to pre upload version.
- Where a datapoint is left blank or has the same value in the upload template, the corresponding system datapoint is not overwritten.
- System aborts upload and warns user when the data is submitted in the incorrect format and file type
- Warnings are provided if data does not meet defined automatic QC criteria (Criteria = extreme slopes or dips and jumps in timeseries; significant differences from replaced/over written variables.)
- Warnings are easily understood and recommend specific troubleshooting steps
- System displays confirmation of a successful upload

**Comment by paradoxxjm** [comment] 2017-07-10 15:13
Issue is a duplicate of #29. Closing.

**Closed as completed by paradoxxjm** 2017-07-10 15:13 UTC
Labels: Set-Up/Initialisation, Inventory Calculations
